[functions]
  external_node_modules = ["express", "body-parser", "request", "https"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[build]
  functions = "functions"
  publish ="public"
  command = "npm run build"